name: Sync Dify to Gitee

on:
  # 监听上游仓库更新
  push:
    branches: [ main ]
  # 定时任务，每天凌晨2点执行
  schedule:
    - cron: '0 2 * * *'
  # 可以手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出当前仓库代码
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 同步上游仓库更新
      - name: 同步上游仓库
        run: |
          git remote add upstream https://github.com/langgenius/dify.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main

      # 同步到码云
      - name: 推送到码云
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
          GITEE_REPO: ${{ secrets.GITEE_REPO }}
        run: |
          git remote add gitee https://$GITEE_USERNAME:$GITEE_PASSWORD@gitee.com/$GITEE_USERNAME/$GITEE_REPO.git
          git push gitee main:main --force